document.addEventListener("DOMContentLoaded",()=>{
const corps=document.getElementById("corps-alertes"),vide=document.getElementById("alertes-vides"),recherche=document.getElementById("recherche-alertes"),filtre=document.getElementById("filtre-statut"),panneau=document.getElementById("traitement-alerte"),formulaire=document.getElementById("formulaire-alerte"),notification=document.getElementById("notification");let alertes=[],alerteActive=null;
const statuts={a_verifier:"À vérifier",en_cours:"En cours",fraude_confirmee:"Fraude confirmée",legitime:"Légitime"};
const date=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?(v||"—"):new Intl.DateTimeFormat("fr-FR",{dateStyle:"short",timeStyle:"short"}).format(d)};
function notifier(message,type="succes"){notification.textContent=message;notification.className=`notification visible ${type}`;setTimeout(()=>notification.className="notification",3500)}
function compteurs(){document.getElementById("compteur-total").textContent=alertes.length;document.getElementById("compteur-verifier").textContent=alertes.filter(a=>a.statut==="a_verifier").length;document.getElementById("compteur-cours").textContent=alertes.filter(a=>a.statut==="en_cours").length;document.getElementById("compteur-confirmees").textContent=alertes.filter(a=>a.statut==="fraude_confirmee").length}
function afficher(){const terme=recherche.value.trim().toLowerCase(),statut=filtre.value;const selection=alertes.filter(a=>(statut==="tous"||a.statut===statut)&&`${a.nom_fichier||""} ${a.category||""}`.toLowerCase().includes(terme));corps.replaceChildren();selection.forEach(a=>{const tr=document.createElement("tr"),p=(Number(a.probabilite_fraude)*100).toFixed(2);tr.innerHTML=`<td><span class="badge-risque risque-eleve">Élevé</span></td><td>${p} %</td><td>${a.nom_fichier||"Analyse individuelle"}</td><td>${a.numero_ligne??"—"}</td><td>${a.category||"—"}</td><td>${a.hour===undefined?"—":`${a.hour} h`}</td><td><span class="badge-statut ${a.statut}">${statuts[a.statut]||a.statut}</span></td><td><button type="button" class="bouton-traiter" data-id="${a.id}">Traiter</button></td>`;corps.appendChild(tr)});vide.textContent=alertes.length?"Aucune alerte ne correspond aux filtres.":"Aucune alerte détectée.";vide.classList.toggle("cache",selection.length>0);compteurs()}
function ouvrir(id){alerteActive=alertes.find(a=>String(a.id)===String(id));if(!alerteActive)return;document.getElementById("titre-alerte").textContent=`Alerte #${alerteActive.id} — ${alerteActive.nom_fichier||"Analyse individuelle"}`;document.getElementById("detail-probabilite").textContent=`${(Number(alerteActive.probabilite_fraude)*100).toFixed(2)} %`;document.getElementById("detail-categorie").textContent=alerteActive.category||"—";document.getElementById("detail-heure").textContent=alerteActive.hour===undefined?"—":`${alerteActive.hour} h`;document.getElementById("detail-date").textContent=date(alerteActive.date_analyse);document.getElementById("statut-alerte").value=alerteActive.statut;document.getElementById("commentaire-alerte").value=alerteActive.commentaire||"";panneau.classList.remove("cache");panneau.scrollIntoView({behavior:"smooth"})}
async function charger(){try{const r=await fetch(`${API_URL}/alertes`,{credentials:"include"});if(!r.ok)throw new Error();alertes=(await r.json()).alertes||[];afficher()}catch{vide.textContent="Impossible de charger les alertes. Vérifiez que FastAPI est démarré.";vide.classList.remove("cache")}}
corps.addEventListener("click",e=>{const b=e.target.closest("[data-id]");if(b)ouvrir(b.dataset.id)});recherche.addEventListener("input",afficher);filtre.addEventListener("change",afficher);document.getElementById("fermer-alerte").addEventListener("click",()=>panneau.classList.add("cache"));
formulaire.addEventListener("submit",async e=>{e.preventDefault();if(!alerteActive)return;const bouton=document.getElementById("enregistrer-alerte");bouton.disabled=true;try{const r=await fetch(`${API_URL}/alertes/${alerteActive.id}`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({statut:document.getElementById("statut-alerte").value,commentaire:document.getElementById("commentaire-alerte").value})});const resultat=await r.json();if(!r.ok)throw new Error(resultat.detail||"Échec de l’enregistrement");Object.assign(alerteActive,resultat);afficher();notifier("La décision de l’analyste a été enregistrée.")}catch(err){notifier(err.message,"erreur")}finally{bouton.disabled=false}});charger();
});
