document.addEventListener("DOMContentLoaded",()=>{
const corps=document.getElementById("corps-utilisateurs"),vide=document.getElementById("utilisateurs-vides"),notification=document.getElementById("notification"),formulaire=document.getElementById("formulaire-utilisateur");let utilisateurs=[];
const date=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?(v||"—"):new Intl.DateTimeFormat("fr-FR",{dateStyle:"short"}).format(d)};
function notifier(message,type="succes"){notification.textContent=message;notification.className=`notification visible ${type}`;setTimeout(()=>notification.className="notification",4000)}
function afficher(){corps.replaceChildren();utilisateurs.forEach(u=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${u.nom}</td><td>${u.identifiant}</td><td><span class="badge-role ${u.role}">${u.role==="administrateur"?"Administrateur":"Analyste"}</span></td><td><span class="badge-etat ${u.actif?"actif":"inactif"}">${u.actif?"Actif":"Inactif"}</span></td><td>${date(u.date_creation)}</td><td><button type="button" class="bouton-activation" data-id="${u.id}" data-actif="${!u.actif}">${u.actif?"Désactiver":"Activer"}</button></td>`;corps.appendChild(tr)});document.getElementById("nombre-utilisateurs").textContent=`${utilisateurs.length} compte(s)`;vide.classList.toggle("cache",utilisateurs.length>0)}
async function charger(){try{const r=await fetch(`${API_URL}/utilisateurs`,{credentials:"include"});if(r.status===403){window.location.replace("dashboard.html");return}if(!r.ok)throw new Error("Liste indisponible");utilisateurs=(await r.json()).utilisateurs||[];afficher()}catch(e){vide.textContent="Impossible de charger les utilisateurs.";vide.classList.remove("cache")}}
formulaire.addEventListener("submit",async e=>{e.preventDefault();const bouton=document.getElementById("creer-utilisateur");bouton.disabled=true;try{const r=await fetch(`${API_URL}/utilisateurs`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({nom:document.getElementById("nom-utilisateur").value.trim(),identifiant:document.getElementById("identifiant-utilisateur").value.trim(),role:document.getElementById("role-utilisateur").value,mot_de_passe:document.getElementById("mot-passe-utilisateur").value})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Création impossible");formulaire.reset();notifier("Le compte utilisateur a été créé.");await charger()}catch(err){notifier(err.message,"erreur")}finally{bouton.disabled=false}});
corps.addEventListener("click",async e=>{const b=e.target.closest("[data-id]");if(!b)return;b.disabled=true;try{const r=await fetch(`${API_URL}/utilisateurs/${b.dataset.id}/activation`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({actif:b.dataset.actif==="true"})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Modification impossible");notifier(d.utilisateur.actif?"Le compte a été activé.":"Le compte a été désactivé.");await charger()}catch(err){notifier(err.message,"erreur");b.disabled=false}});charger();
});
